<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Flowsy.Db.Unity</RootNamespace>
        <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>

        <Title>Flowsy Db Agent</Title>
        <Description>
            Provides functionality to access SQL databases with a configurable set of conventions and options for naming and formatting objects like tables, columns, routines and parameters.
        </Description>

        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/flowsydev/flowsy-net-db-unity</RepositoryUrl>

        <AssemblyVersion>4.0.0</AssemblyVersion>
        <PackageVersion>4.0.0</PackageVersion>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <NoWarn>$(NoWarn);NU5118;NU5128</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CaseON" Version="1.4.0" />
        <PackageReference Include="Dapper" Version="2.1.66" />
        <PackageReference Include="Evolve" Version="3.2.0" />
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
        <PackageReference Include="Ulid" Version="1.4.1" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\Strings.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Strings.es.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Strings.es.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\Strings.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Strings.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Strings.es.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Strings.es.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
