<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Flowsy.Db.Unity</RootNamespace>
        <TargetFramework>netstandard2.1</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>

        <Title>Flowsy Db Agent</Title>
        <Description>
            Provides functionality to access SQL databases with a configurable set of conventions and options for naming and formatting objects like tables, columns, routines and parameters.
        </Description>

        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/flowsydev/flowsy-net-db-unity</RepositoryUrl>

        <PackageVersion>1.0.0</PackageVersion>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <NoWarn>$(NoWarn);NU5118;NU5128</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
    </ItemGroup>

</Project>
