//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowsy.Db.Unity.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Flowsy.Db.Unity.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InvalidConnectionKeyX {
            get {
                return ResourceManager.GetString("InvalidConnectionKeyX", resourceCulture);
            }
        }
        
        internal static string FailedToCreateConnectionUsingProviderX {
            get {
                return ResourceManager.GetString("FailedToCreateConnectionUsingProviderX", resourceCulture);
            }
        }
        
        internal static string ConnecionKeyXAlreadyExists {
            get {
                return ResourceManager.GetString("ConnecionKeyXAlreadyExists", resourceCulture);
            }
        }
        
        internal static string CouldNotResolveConnectionForKeyX {
            get {
                return ResourceManager.GetString("CouldNotResolveConnectionForKeyX", resourceCulture);
            }
        }
        
        internal static string ConnectionKeyCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ConnectionKeyCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        internal static string InvalidUnitOfWorkTypeX {
            get {
                return ResourceManager.GetString("InvalidUnitOfWorkTypeX", resourceCulture);
            }
        }
        
        internal static string MappingForEnumTypeXAlreadyExists {
            get {
                return ResourceManager.GetString("MappingForEnumTypeXAlreadyExists", resourceCulture);
            }
        }
        
        internal static string ProviderXNotSupported {
            get {
                return ResourceManager.GetString("ProviderXNotSupported", resourceCulture);
            }
        }
        
        internal static string InvalidFullyQualifiedNameX {
            get {
                return ResourceManager.GetString("InvalidFullyQualifiedNameX", resourceCulture);
            }
        }
        
        internal static string ConnectionStringCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ConnectionStringCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        internal static string ProviderMustBeSetBeforeConfiguringConventions {
            get {
                return ResourceManager.GetString("ProviderMustBeSetBeforeConfiguringConventions", resourceCulture);
            }
        }
        
        internal static string TypeXIsNotAnEnumType {
            get {
                return ResourceManager.GetString("TypeXIsNotAnEnumType", resourceCulture);
            }
        }
        
        internal static string ProviderXCanNotReturnATableFromRoutineOfTypeY {
            get {
                return ResourceManager.GetString("ProviderXCanNotReturnATableFromRoutineOfTypeY", resourceCulture);
            }
        }
        
        internal static string ProviderXDoesNotSupportRoutineTypeY {
            get {
                return ResourceManager.GetString("ProviderXDoesNotSupportRoutineTypeY", resourceCulture);
            }
        }
        
        internal static string DatabaseTypeNameOrNameTranslatorMustBeProvided {
            get {
                return ResourceManager.GetString("DatabaseTypeNameOrNameTranslatorMustBeProvided", resourceCulture);
            }
        }
        
        internal static string TargetTypeListCannotBeEmpty {
            get {
                return ResourceManager.GetString("TargetTypeListCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string TypeMustBeAnEnum {
            get {
                return ResourceManager.GetString("TypeMustBeAnEnum", resourceCulture);
            }
        }
        
        internal static string MustBeginWorkInvokingMethodX {
            get {
                return ResourceManager.GetString("MustBeginWorkInvokingMethodX", resourceCulture);
            }
        }
        
        internal static string TheWorkHasAlreadyBegunForThisUnit {
            get {
                return ResourceManager.GetString("TheWorkHasAlreadyBegunForThisUnit", resourceCulture);
            }
        }
        
        internal static string CouldNotResolveServiceProvider {
            get {
                return ResourceManager.GetString("CouldNotResolveServiceProvider", resourceCulture);
            }
        }
        
        internal static string CouldNotFindImplementationForTypeX {
            get {
                return ResourceManager.GetString("CouldNotFindImplementationForTypeX", resourceCulture);
            }
        }
        
        internal static string CouldNotFindConstructorForTypeX {
            get {
                return ResourceManager.GetString("CouldNotFindConstructorForTypeX", resourceCulture);
            }
        }
        
        internal static string OnlyOneDefaultConnectionAllowed {
            get {
                return ResourceManager.GetString("OnlyOneDefaultConnectionAllowed", resourceCulture);
            }
        }
        
        internal static string ConnectionKeyMustBeUnique {
            get {
                return ResourceManager.GetString("ConnectionKeyMustBeUnique", resourceCulture);
            }
        }
        
        internal static string NoConnectionOptionsDefined {
            get {
                return ResourceManager.GetString("NoConnectionOptionsDefined", resourceCulture);
            }
        }
        
        internal static string NoMemberFoundForColumnXInTypeY {
            get {
                return ResourceManager.GetString("NoMemberFoundForColumnXInTypeY", resourceCulture);
            }
        }
        
        internal static string NoMatchingConstructorFoundForTypeX {
            get {
                return ResourceManager.GetString("NoMatchingConstructorFoundForTypeX", resourceCulture);
            }
        }
        
        internal static string FailedToCreateConnectionForProviderX {
            get {
                return ResourceManager.GetString("FailedToCreateConnectionForProviderX", resourceCulture);
            }
        }
        
        internal static string DatabaseProviderMustBeSet {
            get {
                return ResourceManager.GetString("DatabaseProviderMustBeSet", resourceCulture);
            }
        }
        
        internal static string ConnectionKeyMustBeSet {
            get {
                return ResourceManager.GetString("ConnectionKeyMustBeSet", resourceCulture);
            }
        }
        
        internal static string ConnectionStringMustBeSet {
            get {
                return ResourceManager.GetString("ConnectionStringMustBeSet", resourceCulture);
            }
        }
        
        internal static string NoConnectionConfigurationsProvided {
            get {
                return ResourceManager.GetString("NoConnectionConfigurationsProvided", resourceCulture);
            }
        }
        
        internal static string NoDefaultConnectionConfigurationFound {
            get {
                return ResourceManager.GetString("NoDefaultConnectionConfigurationFound", resourceCulture);
            }
        }
        
        internal static string CouldNotResolveDefaultConnectionConfiguration {
            get {
                return ResourceManager.GetString("CouldNotResolveDefaultConnectionConfiguration", resourceCulture);
            }
        }
        
        internal static string ConfigurationNotFoundForConnectionIdentifiedByX {
            get {
                return ResourceManager.GetString("ConfigurationNotFoundForConnectionIdentifiedByX", resourceCulture);
            }
        }
        
        internal static string SessionForConnectionXNotParticipatingInTransaction {
            get {
                return ResourceManager.GetString("SessionForConnectionXNotParticipatingInTransaction", resourceCulture);
            }
        }
        
        internal static string SessionForConnectionXIsAlreadyParticipatingInTransaction {
            get {
                return ResourceManager.GetString("SessionForConnectionXIsAlreadyParticipatingInTransaction", resourceCulture);
            }
        }
        
        internal static string ScriptXNotFound {
            get {
                return ResourceManager.GetString("ScriptXNotFound", resourceCulture);
            }
        }
        
        internal static string NoMigrationConfigurationProvided {
            get {
                return ResourceManager.GetString("NoMigrationConfigurationProvided", resourceCulture);
            }
        }
        
        internal static string DirectoryXNotFound {
            get {
                return ResourceManager.GetString("DirectoryXNotFound", resourceCulture);
            }
        }
        
        internal static string ConnectionXIsNotDbConnection {
            get {
                return ResourceManager.GetString("ConnectionXIsNotDbConnection", resourceCulture);
            }
        }
    }
}
