//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowsy.Db.Unity.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Flowsy.Db.Unity.Resources.Strings_es", typeof(Strings_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InvalidConnectionKeyX {
            get {
                return ResourceManager.GetString("InvalidConnectionKeyX", resourceCulture);
            }
        }
        
        internal static string FailedToCreateConnectionUsingProviderX {
            get {
                return ResourceManager.GetString("FailedToCreateConnectionUsingProviderX", resourceCulture);
            }
        }
        
        internal static string ConnecionKeyXAlreadyExists {
            get {
                return ResourceManager.GetString("ConnecionKeyXAlreadyExists", resourceCulture);
            }
        }
        
        internal static string CouldNotResolveConnectionForKeyX {
            get {
                return ResourceManager.GetString("CouldNotResolveConnectionForKeyX", resourceCulture);
            }
        }
        
        internal static string ConnectionKeyCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ConnectionKeyCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        internal static string InvalidUnitOfWorkTypeX {
            get {
                return ResourceManager.GetString("InvalidUnitOfWorkTypeX", resourceCulture);
            }
        }
        
        internal static string MappingForEnumTypeXAlreadyExists {
            get {
                return ResourceManager.GetString("MappingForEnumTypeXAlreadyExists", resourceCulture);
            }
        }
        
        internal static string ProviderXNotSupported {
            get {
                return ResourceManager.GetString("ProviderXNotSupported", resourceCulture);
            }
        }
        
        internal static string InvalidFullyQualifiedNameX {
            get {
                return ResourceManager.GetString("InvalidFullyQualifiedNameX", resourceCulture);
            }
        }
        
        internal static string ConnectionStringCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ConnectionStringCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}
